name: cashapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.14.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0
  ussd_advanced: ^0.1.2
  json_serializable: ^6.0.1
  path_provider: ^2.0.4

  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.2


flutter:
  generate: true
  uses-material-design: true

